name: Docker Build and Push

on:
    workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set commit hash
        id: set_commit_hash
        run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - 
        name: Echo commit hash
        run: echo ${{ steps.set_commit_hash.outputs.hash }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nearby-restaurants:${{ steps.set_commit_hash.outputs.hash }}

