name: Google Cloud Deploy

on: workflow_dispatch

jobs:
  gcloud_auth:
    runs-on: ubuntu-latest
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCLOUD_GSA_JSON }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'
 
    - name: Configure kubectl
      run: |
        gcloud components install gke-gcloud-auth-plugin
        gcloud auth configure-docker europe-north1-docker.pkg.dev
        gcloud container clusters get-credentials restaurant-finder-cluster --location=europe-north1
 