name: On Pull Request

on: pull_request

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.12  # Replace with your desired Python version

      - name: Install dependencies
        run: pip3 install -r requirements.txt
      
      - name: Run Pylint
        run: pylint src test --fail-under=10

      - name: Run tests with code coverage
        run: pytest --cov-report=xml --cov=src test/

     # - name: Generate HTML coverage report
     #   run: coverage html

     # - name: Upload coverage report
     #   uses: actions/upload-artifact@v2
     #   with:
     #     name: coverage-report
     #     path: htmlcov  # Path to the coverage report directory

      - name: Post coverage report as a comment
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml

#jobs:
#    build:
#        name: Pull Request Build and Test
#        runs-on: ubuntu-latest

#        steps:
#            - name: Checkout code
#              uses: actions/checkout@v2

#            - name: Build docker/build
#              uses: docker/build-push-action@v2
#              with:
#               context: .
#               file: ./docker/build
#                push: false
#                tags: pull_request
#            - name: List docker images
#              run: docker images
